### ISSUE TITLE
test failing with varnish 6.6

### ISSUE THREAD

**Issue by blacktek** [nigoroll/libvmod-dynamic#74]
Hello,
  we just installed this library on Varnish 6.6 and One of tests failed (out of 21):

*** v1 CLI RX 106
**** v1 CLI RX|Message from VCC-compiler:
**** v1 CLI RX|Expected '{' got '+'
**** v1 CLI RX|(program line 560), at
**** v1 CLI RX|('<vcl.inline>' Line 7 Pos 27)
**** v1 CLI RX| acl ipv4_loopback +log {
**** v1 CLI RX|--------------------------#-----
**** v1 CLI RX|
**** v1 CLI RX|Running VCC-compiler failed, exited with 2
**** v1 CLI RX|VCL compilation failed

18 varnish v1 -vcl {
19 import ${vmod_dynamic};
20
21 backend dummy { .host = "${bad_ip}"; .port = "9080"; }
22
23 acl ipv4_loopback +log {
24 "127/24";
25 }
26
27 sub vcl_init {
28 new d1 = dynamic.director(
29 port = "${s1_port}",
30 whitelist = ipv4_loopback,
31 domain_usage_timeout = 1s);
32 d1.debug(true);
33 }
34
35 sub vcl_recv {
36 set req.backend_hint = d1.backend();
37 }
38 } -start

Could you please make it working with Varnish 6.6?

What are the consequences of the failed test?

Thank you
