### ISSUE TITLE
Compile error in varnish 6.0.1-1~stretch

### ISSUE THREAD

**Issue by razvanphp** [nigoroll/libvmod-dynamic#48]
We are using tag 6.0, where you backported some refactorings and we are now getting the following error:

```
In file included from vmod_dynamic.c:56:0:
vmod_dynamic.h:88:2: error: unknown type name ‘vtim_real’
  vtim_real   deadline;
  ^~~~~~~~~
vmod_dynamic.h:137:2: error: unknown type name ‘vtim_real’
  vtim_real   deadline;
  ^~~~~~~~~
vmod_dynamic.c:410:17: error: unknown type name ‘vtim_real’
     void *priv, vtim_real now)
                 ^~~~~~~~~
vmod_dynamic.c: In function ‘dynamic_lookup_thread’:
vmod_dynamic.c:474:2: error: unknown type name ‘vtim_real’
  vtim_real lookup, results, update;
  ^~~~~~~~~
vmod_dynamic.c:498:4: error: implicit declaration of function ‘dynamic_update_domain’ [-Werror=implicit-function-declaration]
    dynamic_update_domain(dom, res, res_priv, results);
    ^~~~~~~~~~~~~~~~~~~~~
At top level:
vmod_dynamic.c:311:1: error: ‘dynamic_add’ defined but not used [-Werror=unused-function]
 dynamic_add(VRT_CTX, struct dynamic_domain *dom, const struct res_info *info)
 ^~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [vmod_dynamic.lo] Error 1
make[1]: ***
```

**Comment by nigoroll** [comment]
I have re-checked the build both with and without getdns and `varnish-6.0.3 revision 4c946b933fdb4cce124d5b34b9b8b9dbb696bdaf` and do not see this issue.

Can you please update and re-check?

Nils

**Comment by razvanphp** [comment]
ok, it worked with 6.0.3, but this one is only in LTS repo, we were using this one where 6.0.1 is the latest version: https://packagecloud.io/varnishcache/varnish60

Thank you, but still, isn't this a breaking change on a minor version?

**Comment by nigoroll** [comment]
Fixing this would not be a big deal, but I just don't see a point in supporting minor versions of old releases.
6.0.3 is in https://packagecloud.io/varnishcache/varnish60lts so I guess updating to a supported LTS would make most sense.

**Comment by razvanphp** [comment]
but would you be so kind at least to tell us a git commit hash that would compile on 6.0.1? I tried f5423ed96bd3daec10137fdf52b572f363c1b0a6 from 27 Apr but it still failed...

On LTS repo, it seems that there are some differences in deb packaging, the daemon runs under `vcache` user instead of `varnish` and this causes other problems.

Thank you!

**Comment by nigoroll** [comment]
I do not have a sponsor for this kind of support of eol versions, please contact me directly if you are interested in supporting it.
